- activemq-camel/pom.xml
- activemq-camel/src/test/java/org/apache/activemq/camel/JmsJdbcXARollbackTest.java
- activemq-camel/src/test/java/org/apache/activemq/camel/JmsJdbcXATest.java
- activemq-camel/src/test/resources/org/apache/activemq/camel/jmsXajdbc.xml
- activemq-camel/src/test/resources/org/apache/activemq/camel/jmsXajdbcRollback.xml
- activemq-unit-tests/pom.xml
- activemq-unit-tests/src/test/resources/org/apache/activemq/usecases/activemq.xml
- activemq-unit-tests/src/test/resources/org/apache/activemq/xbean/activemq.xml
- assembly/pom.xml
- assembly/src/main/descriptors/common-bin.xml
- assembly/src/release/examples/conf/activemq-demo.xml
- assembly/src/release/examples/conf/activemq-jdbc-performance.xml
- assembly/src/release/examples/conf/activemq-jdbc.xml
- pom.xml
AMQ-5636 - Update DBCP to a much more recent version
> AMQ-5636 - Update DBCP to a much more recent version

- activemq-http/pom.xml
- activemq-http/src/main/java/org/apache/activemq/transport/util/HttpTransportUtils.java
- activemq-http/src/main/java/org/apache/activemq/transport/ws/AbstractMQTTSocket.java
- activemq-http/src/main/java/org/apache/activemq/transport/ws/AbstractStompSocket.java
- activemq-http/src/main/java/org/apache/activemq/transport/ws/jetty8/MQTTSocket.java
- activemq-http/src/main/java/org/apache/activemq/transport/ws/jetty8/StompSocket.java
- activemq-http/src/main/java/org/apache/activemq/transport/ws/jetty8/WSServlet.java
- activemq-http/src/main/java/org/apache/activemq/transport/ws/jetty9/MQTTSocket.java
- activemq-http/src/main/java/org/apache/activemq/transport/ws/jetty9/StompSocket.java
- activemq-http/src/main/java/org/apache/activemq/transport/ws/jetty9/WSServlet.java
- activemq-http/src/test/java/org/apache/activemq/transport/util/HttpTransportUtilsTest.java
- activemq-http/src/test/java/org/apache/activemq/transport/ws/SocketTest.java
StompSocket and MQTTSocket will now return the appropriate web socket
remote address based on the HttpRequestServlet that initialized
the web socket connection.
> https://issues.apache.org/jira/browse/AMQ-5865

- activemq-broker/src/main/java/org/apache/activemq/store/memory/MemoryMessageStore.java
Fixing a potential Null pointer exception in  MemoryMessageStore
> https://issues.apache.org/jira/browse/AMQ-5748

- activemq-camel/src/main/java/org/apache/activemq/camel/component/broker/BrokerProducer.java
- activemq-camel/src/test/java/org/apache/activemq/camel/component/broker/BrokerComponentXMLConfigTest.java
- activemq-camel/src/test/resources/org/apache/activemq/camel/component/broker/camel.xml
AMQ-5903 - add patch that fixes the broker camel component to take all header values
> AMQ-5903 - add patch that fixes the broker camel component 

- pom.xml
Updating netty to version 4.0.31
> https://issues.apache.org/jira/browse/AMQ-5982

- activemq-broker/src/main/java/org/apache/activemq/plugin/SubQueueSelectorCacheBroker.java
- activemq-broker/src/test/java/org/apache/activemq/plugin/SubQueueSelectorCacheBrokerWildcardTest.java
Parsing message selector for wildcard matches for ignoreWildcardSelectors feature.
https://issues.apache.org/jira/browse/AMQ-6036
> AMQ-6036: Parsing message selector for wildcard matches

- activemq-karaf/pom.xml
Hi,
This PR is related to:
https://issues.apache.org/jira/browse/AMQ-6181
Thanks
Andrea
> https://issues.apache.org/jira/browse/AMQ-6181 - Upgrade to Joda-time 2.9

- activemq-client/src/main/java/org/apache/activemq/command/ActiveMQBytesMessage.java
- activemq-unit-tests/src/test/java/org/apache/activemq/bugs/AMQ6244Test.java
Fix and test for https://issues.apache.org/jira/browse/AMQ-6244
> https://issues.apache.org/jira/browse/AMQ-6244

- activemq-client/src/main/java/org/apache/activemq/jndi/ActiveMQSslInitialContextFactory.java
- activemq-unit-tests/src/test/java/org/apache/activemq/jndi/ActiveMQSslInitialContextFactoryTest.java
Add support for SSL configurations using JNDI.
> https://issues.apache.org/jira/browse/AMQ-6489

- activemq-karaf/src/main/resources/features-core.xml
- activemq-osgi/pom.xml
Please backport this to 2.14.x too
> [AMQ-6576] Problem while installing activemq-camel with Camel 2.17.x or 2.18.x

- activemq-client/src/main/java/org/apache/activemq/util/DataByteArrayInputStream.java
- activemq-client/src/main/java/org/apache/activemq/util/DataByteArrayOutputStream.java
- activemq-client/src/main/java/org/apache/activemq/util/MarshallingSupport.java
- activemq-kahadb-store/src/main/java/org/apache/activemq/store/kahadb/disk/util/DataByteArrayInputStream.java
- activemq-kahadb-store/src/main/java/org/apache/activemq/store/kahadb/disk/util/DataByteArrayOutputStream.java
that are based on Apache Harmony code.  This also avoid some code duplication that was occurring.
> Add new implementations of the writeUTF8 and readUTF8 methods 

- activemq-broker/src/main/java/org/apache/activemq/broker/region/AbstractRegion.java
- activemq-unit-tests/src/test/java/org/apache/activemq/RemoveDestinationTest.java
From the web console, this will do a purge of the destination before deleting.
> AMQ-7135 : do a purge before deleting the destination

- pom.xml
Update the Spring + Camel versions to remove a few CVE reports.
> Updating Spring + Camel versions

- pom.xml
Update OWasp dependency check plugin version
> Update OWasp dependency check plugin version

- activemq-karaf/pom.xml
- activemq-osgi/pom.xml
- activemq-web/pom.xml
- activemq-web/src/main/java/org/apache/activemq/web/view/RssMessageRenderer.java
- assembly/src/main/descriptors/common-bin.xml
- pom.xml
Tested Atom + RSS feeds in webconsole work after the change.
> AMQ-7216 - Update Rome dependency

- activemq-amqp/src/main/java/org/apache/activemq/transport/amqp/protocol/AmqpSender.java
- activemq-broker/src/main/java/org/apache/activemq/broker/TransportConnection.java
- activemq-broker/src/main/java/org/apache/activemq/broker/region/Queue.java
- activemq-client/src/main/java/org/apache/activemq/transport/discovery/DiscoveryTransport.java
- activemq-client/src/main/java/org/apache/activemq/transport/tcp/TcpTransportFactory.java
- activemq-client/src/main/java/org/apache/activemq/util/ClassLoadingAwareObjectInputStream.java
- activemq-mqtt/src/main/java/org/apache/activemq/transport/mqtt/MQTTProtocolConverter.java
- activemq-ra/src/main/java/org/apache/activemq/ra/ServerSessionImpl.java
I am sure the wording can be improved.
I tried to copy the wording from similar log messages if there were any.
> Fix unused format arguments in log messages.

- pom.xml
Credit To: Piyush Chugh <chughpiyush>
> Cleanup unused properties from pom.xml

- activemq-partition/pom.xml
- assembly/pom.xml
Credit To: Piyush Chugh <chughpiyush>
> [AMQ-7409] Exclude netty from zookeeper dependency

- activemq-amqp/src/test/java/org/apache/activemq/transport/amqp/client/AmqpConnection.java
- activemq-broker/src/main/java/org/apache/activemq/broker/BrokerService.java
- activemq-broker/src/main/java/org/apache/activemq/broker/jmx/NetworkDestinationView.java
- activemq-broker/src/main/java/org/apache/activemq/broker/region/Topic.java
- activemq-broker/src/main/java/org/apache/activemq/broker/region/cursors/StoreDurableSubscriberCursor.java
- activemq-broker/src/main/java/org/apache/activemq/broker/region/cursors/TopicStorePrefetch.java
- activemq-broker/src/main/java/org/apache/activemq/broker/region/policy/AbortSlowAckConsumerStrategy.java
- activemq-broker/src/main/java/org/apache/activemq/network/DemandForwardingBridgeSupport.java
- activemq-broker/src/main/java/org/apache/activemq/network/jms/DestinationBridge.java
- activemq-broker/src/test/java/org/apache/activemq/JmsTransactionTestSupport.java
- activemq-client/src/main/java/org/apache/activemq/ActiveMQMessageConsumer.java
- activemq-client/src/main/java/org/apache/activemq/jndi/JNDIReferenceFactory.java
- activemq-client/src/main/java/org/apache/activemq/transport/AbstractInactivityMonitor.java
- activemq-client/src/main/java/org/apache/activemq/transport/discovery/multicast/MulticastDiscoveryAgent.java
- activemq-client/src/main/java/org/apache/activemq/util/IdGenerator.java
- activemq-http/src/test/java/org/apache/activemq/transport/ws/MQTTWSConnection.java
- activemq-jaas/src/main/java/org/apache/activemq/jaas/PropertiesLoader.java
- activemq-jms-pool/src/main/java/org/apache/activemq/jms/pool/PooledConnection.java
- activemq-jms-pool/src/test/java/org/apache/activemq/jms/pool/JmsPoolTestSupport.java
- activemq-kahadb-store/src/main/java/org/apache/activemq/store/kahadb/MultiKahaDBPersistenceAdapter.java
- activemq-mqtt/src/main/java/org/apache/activemq/transport/mqtt/MQTTProtocolConverter.java
- activemq-ra/src/main/java/org/apache/activemq/ra/ActiveMQResourceAdapter.java
- activemq-ra/src/main/java/org/apache/activemq/ra/LocalAndXATransaction.java
This is a cleanup of the old PR: https://github.com/apache/activemq/pull/257
I didn't merge the first commit "Utilize parameterized logging and remove calls to toString() " - as it contained a lot of errors.
This supercedes https://github.com/apache/activemq/pull/257 which can be closed.
> AMQ-7413 - Misc logging fixes

- assembly/pom.xml
- assembly/src/main/descriptors/common-bin.xml
- pom.xml
TODO: web console deployment doesn't work on Karaf due to NPE. I'm working on it.
> [AMQ-7388] Upgrade to Jetty 9.4.27.20200227

- activemq-web-console/src/main/java/org/apache/activemq/web/controller/PauseDestination.java
- activemq-web-console/src/main/java/org/apache/activemq/web/controller/ResumeDestination.java
- activemq-web-console/src/main/webapp/WEB-INF/dispatcher-servlet.xml
- activemq-web-console/src/main/webapp/queues.jsp
https://issues.apache.org/jira/browse/AMQ-7499
As wished in [AMQ-5229](https://issues.apache.org/jira/browse/AMQ-5229?focusedCommentId=14336865&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14336865) I extended queues overview with operations to pause and resume a single queue.
> AMQ-7499 add pause/resume operation of a queue in web console

- README.md
- activemq-unit-tests/src/test/java/org/apache/activemq/broker/BrokerBenchmark.java
- Improves the README by using HTTPS links and fixing some outdated links
- Fixes unintended String concatenation
Please let me know if the commits should have different messages.
----
Sorry, but I won't sign a CLA for this. Feel free to close this pull request if you require a CLA for these changes.
> README and minor code fix

- pom.xml
> Upgrade to Jetty 9.4.38.v20210224

- pom.xml
> Update shiro to 1.7.1

- activemq-http/src/main/java/org/apache/activemq/transport/http/HttpTransportServer.java
- activemq-http/src/main/java/org/apache/activemq/transport/ws/WSTransportServer.java
- assembly/src/release/conf/jetty.xml
Fixes:
* Console
* WS transport
* HTTP transport
> AMQ-6951 Hide jetty version

- pom.xml
- Confirm update w/ deprecation fixes
> [AMQ-8284] Update jetty to 9.4.41.v20210516

- activemq-client/src/main/java/org/apache/activemq/transport/tcp/TcpTransport.java
https://issues.apache.org/jira/browse/AMQ-8304
> AMQ-8304: Added a check with !isStopping() also before attempting to read input stream

- assembly/pom.xml
- assembly/src/main/descriptors/common-bin.xml
- assembly/src/main/descriptors/unix-bin.xml
- assembly/src/main/descriptors/windows-bin.xml
- pom.xml
- Convert 'attached' to 'single' goal
- Clean up leading "/" in descriptors
> [AMQ-8290] Cleanup assembly warnings and upgrade assembly plugin

- activemq-web/src/main/java/org/apache/activemq/web/view/XmlMessageRenderer.java
Fix XmlMessageRenderer has the risk of XStream deserialization, thanks
> [AMQ-8348] Fix XmlMessageRenderer has the risk of XStream deserialization

- activemq-stomp/src/test/java/org/apache/activemq/transport/stomp/StompTest.java
- pom.xml
CVE ref: https://nvd.nist.gov/vuln/detail/CVE-2021-39154
> [AMQ-8358] Update xstream to 1.4.18

- activemq-broker/src/main/java/org/apache/activemq/broker/jmx/ManagementContext.java
I don't have all the rational of JmxRegistry impl but the comment tend to mean it was a lazy implementation so let's do a portable lazy implementation and not one preventing the project to compile until you tune your environment/IDE/maven.
> Ensure to not depend on sun.rmi.registry.RegistryImpl

- activemq-broker/src/main/java/org/apache/activemq/broker/jmx/NetworkConnectorView.java
- activemq-broker/src/main/java/org/apache/activemq/broker/jmx/NetworkConnectorViewMBean.java
- activemq-broker/src/main/java/org/apache/activemq/network/DemandForwardingBridgeSupport.java
- activemq-broker/src/main/java/org/apache/activemq/network/NetworkBridgeConfiguration.java
> [AMQ-8413] Add remoteUserName and remotePassword config fields

- activemq-broker/src/main/java/org/apache/activemq/broker/jmx/DestinationView.java
- activemq-broker/src/main/java/org/apache/activemq/broker/jmx/DestinationViewMBean.java
- activemq-broker/src/main/java/org/apache/activemq/broker/region/BaseDestination.java
- activemq-broker/src/main/java/org/apache/activemq/broker/region/Destination.java
- activemq-broker/src/main/java/org/apache/activemq/broker/region/DestinationFilter.java
- activemq-broker/src/main/java/org/apache/activemq/broker/region/DestinationStatistics.java
- activemq-broker/src/main/java/org/apache/activemq/broker/region/policy/PolicyEntry.java
- Default 'true' to match existing behavior
- Added counter to DestinationView
> [AMQ-8397] Add a destination option to sendDuplicateFromStoreToDLQ

- activemq-kahadb-store/src/main/java/org/apache/activemq/store/kahadb/scheduler/JobSchedulerImpl.java
We recently encountered a similar performance degradation as is described here: https://issues.apache.org/jira/browse/AMQ-7340 
A specific example we encountered was with around 20k messages scheduled very quickly where each message adds 100ms delay times with the previous message.
Example:
message 1 > delay time 100ms
message 2 > delay time 200ms
message 3 > delay time 300ms
...
message 10,000 >> delay time 1000000ms (1000s)
...
message 20,000 >> delay time 2000000ms (2000s)
If delivered on schedule all these messages should be moved to the queue within ~33 minutes but we observed that it took nearly 3 hours for all the messages to be moved to the queue. 
After diving deep on the issue it seems the main loop that processes scheduled messages process them by traversing the B+ Tree index …
> [AMQ-7340] Improve scheduled message performance

- SECURITY.md
It's good security practice to add a SECURITY.md to a github repo, containing details of supported versions, where to find CVEs and how to report new issues.
Feel free to modify as required.
> Adding SECURITY.md for ActiveMQ

- pom.xml
Aligns main branch behaviour with proposed 5.16.x branch changes in #768
> AMQ-8489: fail build quickly+obviously if not run on Java 11+

- activemq-broker/src/main/java/org/apache/activemq/broker/region/BaseDestination.java
- activemq-broker/src/main/java/org/apache/activemq/broker/region/policy/PolicyEntry.java
- activemq-runtime-config/src/test/java/org/apache/activemq/PolicyEntryTest.java
- activemq-runtime-config/src/test/resources/org/apache/activemq/policyEntryTest-policy-sendDuplicateFromStoreToDLQ-mod.xml
- activemq-unit-tests/src/test/java/org/apache/activemq/broker/policy/SendDuplicateFromStoreToDLQTest.java
> [AMQ-8440] Set sendDuplicateFromStoreToDLQ to 'false' by default

- activemq-client/pom.xml
set xstream osgi import optional to align with with its 'provided' dependency declaration
> AMQ-8569: set xstream osgi import optional

- activemq-unit-tests/pom.xml
- pom.xml
- Exclude problematic unit tests
> [AMQ-8567] Upgrade maven-surefire-plugin to 3.0.0-M6

- activemq-web-console/src/main/webapp/js/css.js
- activemq-web-console/src/main/webapp/js/plotkit/SVG.js
- activemq-web-console/src/main/webapp/js/plotkit/SweetCanvas.js
- activemq-web-console/src/main/webapp/js/plotkit/SweetSVG.js
- activemq-web-demo/src/main/webapp/js/amq.js
- activemq-web-demo/src/main/webapp/js/amq_jquery_adapter.js
- activemq-web-demo/src/main/webapp/js/chat.js
- activemq-web-demo/src/main/webapp/mqtt/chat.js
- activemq-web-demo/src/main/webapp/portfolio/portfolio.js
- activemq-web/src/main/resources/org/apache/activemq/web/behaviour.js
- assembly/src/release/examples/conf/camel.xml
- assembly/src/release/examples/mqtt/websocket/index.html
- one clear error
- avoid some implicit variable declarations
- minor beautifications
> fix encoding error in chat.js

- activemq-broker/src/main/java/org/apache/activemq/plugin/StatisticsBrokerPlugin.java
- activemq-runtime-config/src/main/java/org/apache/activemq/plugin/UpdateVirtualDestinationsTask.java
Hello,
While viewing the [MAPREDUCE-4262](https://issues.apache.org/jira/browse/MAPREDUCE-4262), I found that the logging statements might give inaccurate messages. 
I also found that the in the line 93 of the file [UpdateVirtualDestinationsTask](https://github.com/apache/activemq/blob/b3c2c49f96bebee14b74c6456feb233e0312724b/activemq-runtime-config/src/main/java/org/apache/activemq/plugin/UpdateVirtualDestinationsTask.java#L93), the log messages says "Removing virtual destination  ". However, the removing action should already completed in previous code (line 92).
```
plugin.virtualDestinationRemoved(connectionContext, removedVirtualDest);                            
LOG.info("Removing virtual destination: {}", removedVirtualDest); 
```
Would it be better if we change the verb "Removing" …
> [AMQ-8601] Refine the logging messages

- activemq-client/src/main/java/org/apache/activemq/filter/ComparisonExpression.java
- activemq-client/src/main/java/org/apache/activemq/filter/LogicExpression.java
- activemq-client/src/main/java/org/apache/activemq/filter/UnaryExpression.java
Improve performance of Equals and Not operators by providing specific implementations of "matches"
see https://issues.apache.org/jira/browse/AMQ-9052
This is porting of this commit from the Pulsar JMS repository
https://github.com/datastax/pulsar-jms/commit/dc854a24080781474fc3b8076a58ba5a7f231b16
> AMQ-9052: Selectors - improve perfomance of Equals and Not

- activemq-kahadb-store/src/main/java/org/apache/activemq/store/kahadb/KahaDBStore.java
- activemq-kahadb-store/src/main/java/org/apache/activemq/store/kahadb/KahaDBTransactionStore.java
- Removing unused variable `concurrentStoreAndDispatchTransactions` in `KahaDBStore`.
- Cleaning up some dead code and conditions that are always true.
- Ran a full build and tests
> [NO JIRA] Removing unused variable `concurrentStoreAndDispatchTransactions` in `KahaDBStore`

- activemq-broker/src/main/java/org/apache/activemq/broker/jmx/ManagedRegionBroker.java
Running a profiler while executing the sample code attached to [AMQ-9107](https://issues.apache.org/jira/browse/AMQ-9107) identified ManagedRegionBroker.removeConsumer as the bottleneck. The existing implementation loops over all the subscriptions to find the subscription for the consumer we want to close. When we have n consumers and we want to close them all this for loop is O(n^2) and when n is big enough it creates a serious performance issue. With 188,000 consumers we observe the CPU at 100% for ~40 minutes while all the connections are closed: 
After this PR, running the same test case we observe a spike in CPU of only one minute or less, similar to what it took to create the consumers: 
I ran the full suite of tests and everything is passing.
> [AMQ-9107] Remove consumers more efficiently in ManagedRegionBroker

- activemq-console/pom.xml
- activemq-http/pom.xml
- activemq-karaf/src/main/resources/features-core.xml
- activemq-web-demo/pom.xml
- assembly/src/main/descriptors/common-bin.xml
- pom.xml
> [AMQ-8572] Remove unused commons-lang3 dependency

- activemq-broker/src/main/java/org/apache/activemq/broker/Connector.java
- activemq-broker/src/main/java/org/apache/activemq/broker/TransportConnector.java
- activemq-broker/src/main/java/org/apache/activemq/broker/jmx/ConnectorView.java
- activemq-broker/src/main/java/org/apache/activemq/broker/jmx/ConnectorViewMBean.java
- activemq-unit-tests/src/test/java/org/apache/activemq/broker/jmx/TransportConnectorMBeanTest.java
Jenkins CI hung up on that AMQ7118 test.
> [AMQ-9163] Add 'Started' attribute to ConnectorView

- activemq-client/src/main/java/org/apache/activemq/ActiveMQMessageConsumer.java
- activemq-unit-tests/src/test/java/org/apache/activemq/RedeliveryPolicyTest.java
Scenario on client:
1. Employing RedeliveryPolicy with exponential backoff (keeping maximum
redeliveries at default 6)
2. Enabled non-blocking redelivery
3. Receiving e.g. 100 consecutive poison messages (which eventually
should DLQ after max redeliveries)
This will result in massive redelivery delays due to a logic bug.
The reason is that redeliveryDelay is a field variable kept on the
ActiveMQMessageConsumer, instead of being a property on the message - or
that the redelivery delay was calculated per message based on the
redelivery count.
When consecutive messages rollbacks multiple times, the redeliveryDelay
field is continuously multiplied by the backoff multiplier, resulting in
enormous delays.
Fix: Ditch the field variable, instead calculating the redeliveryDelay
per delivery from …
> AMQ-8617: RedeliveryPolicy:Exponential Backoff + NonBlockingRedelivery = too long delays

- activemq-unit-tests/src/test/java/org/apache/activemq/advisory/AdvisoryTests.java
Properly shutdown broker for each test and speed up tests by sending less messages
> AMQ-9192 - Fix flaky AdvisoryTests

- activemq-jdbc-store/pom.xml
- activemq-jdbc-store/src/main/java/org/apache/activemq/store/jdbc/adapter/DefaultJDBCAdapter.java
- No need to drag JAXB dependency just for a base64 converter
> [AMQ-9324] Convert activemq-jdbc-store to use j.util.Base64

- assembly/src/docker/Dockerfile
- assembly/src/release/bin/activemq
- assembly/src/release/bin/setenv
> Revert "AMQ-9460: Don't override ACTIVEMQ_OPTS when provided by user"

- activemq-broker/src/main/java/org/apache/activemq/broker/Broker.java
* Fixed a few typos in the comments
* Remove one redundant public modifier
* Added more documentation to param tags and methods.
> [Misc] Various misc. fixes for Broker interface

- pom.xml
Upgrade owasp dependency check to 9.2.0
> Upgrade owasp dependency check

- activemq-broker/src/main/java/org/apache/activemq/advisory/AdvisoryBroker.java
Iteration over collections or arrays  can be replaced with an enhanced for loop (foreach iteration syntax). 
```
The for-each construct gets rid of the clutter and the opportunity for error.
When should you use the for-each loop? Any time you can. It really beautifies your code.
```
See more details why : https://docs.oracle.com/javase/8/docs/technotes/guides/language/foreach.html
> for loop can be replaced with enhanced for

- README.md
To separate paragraphs, now it looks like
> Add break line to README

- activemq-broker/src/main/java/org/apache/activemq/broker/region/virtual/BaseVirtualDestinationFilter.java
- activemq-broker/src/main/java/org/apache/activemq/broker/region/virtual/MappedQueueFilter.java
Addressing the comment from https://github.com/apache/activemq/pull/1247
> [AMQ-9530] Removed unused imports.

- activemq-client/src/main/java/org/apache/activemq/transport/tcp/QualityOfServiceUtils.java
- activemq-unit-tests/src/test/java/org/apache/activemq/transport/tcp/QualityOfServiceUtilsTest.java
Not sure what to return in the end of method - used value -1 for now.
> AMQ-9723 implemented try with resources for socket

- activemq-unit-tests/src/test/java/org/apache/activemq/broker/policy/SendDuplicateFromStoreToDLQTest.java
Parameterize test to cover all combinations of policyEntry settings
sendDuplicateFromStoreToDLQ
cacheEnabled
auditEnabled
optimizedDispatch
> [AMQ-9654] Enhance SendDuplicateFromStoreToDLQTest
