activemq-broker/src/main/java/org/apache/activemq/store/SharedFileLocker.java
activemq-unit-tests/src/test/java/org/apache/activemq/store/SharedFileLockerTest.java

https://issues.apache.org/jira/browse/AMQ-5709
This is about changing how the Log is done in case of not being able to lock (log only once)

AMQ-5709 Reworking Logging on Locker

---

activemq-broker/src/main/java/org/apache/activemq/network/jms/DestinationBridge.java
activemq-unit-tests/src/test/java/org/apache/activemq/xbean/DestinationBridgeAccessorsTest.java
activemq-unit-tests/src/test/resources/handleReplyToActivemq.xml

Includes unit test DestinationBridgeAccessorsTest which replicated the problem and now passes.

AMQ-5713 - making accessors public to remove startup error.

---

activemq-broker/src/main/java/org/apache/activemq/advisory/AdvisoryBroker.java
activemq-unit-tests/src/test/java/org/apache/activemq/advisory/AdvisoryTests.java

Modifing the AdivsoryBroker to set the originBrokerURL to the transport connector's
URL if it has been set versus using a default URL.

https://issues.apache.org/jira/browse/AMQ-5705

---

activemq-kahadb-store/src/main/java/org/apache/activemq/store/kahadb/KahaDBStore.java
activemq-kahadb-store/src/main/java/org/apache/activemq/store/kahadb/MultiKahaDBPersistenceAdapter.java
activemq-unit-tests/src/test/java/org/apache/activemq/store/kahadb/MultiKahaDBTopicDeletionTest.java

Resolves an issue when using mKahaDB that caused a MessageStore
being used by more than one destination to be deleted even though
there was still at least 1 other destination using the store.

https://issues.apache.org/jira/browse/AMQ-5875

---

assembly/src/release/bin/activemq

Add LSB headers to init script to fix problems when setting up ActiveMQ
as a daemon with chkconfig on RHEL and clones.
See: https://issues.apache.org/jira/browse/AMQ-5977
Signed-off-by: Gregor Zurowski <gregor@zurowski.org>

AMQ-5977: Add LSB headers to init script

---

activemq-web-console/src/main/java/org/apache/activemq/web/controller/RetryMessage.java
activemq-web-console/src/main/webapp/WEB-INF/dispatcher-servlet.xml
activemq-web-console/src/main/webapp/message.jsp
activemq-web/src/main/java/org/apache/activemq/web/MessageQuery.java

ActiveMQ Dead letter queues are defined in runtime by individual or shared DLQ strategy. However, in the web console, the retry command is only active if a queue starts with "DLQ." or "DLT.". More, it does not really do a retry, only a move from DLQ.<queuename> to <queuename>. This is not correct, since a DLQ strategy might use other prefix/suffix to name a DLQ. The correct original destination is taken from a property of the message, not derived from the DLQ queue name.
This PR enables the retry command on configured DLQs, regardless of name. By some reason the default ActiveMQ.DLQ is not detected as a DLQ (looking at JMX properties of the queue), so this particular queue is also included to show the retry command. The retry command actually triggers the retry JMX operation.
This PR is …

AMQ-5662 improve Web Console to support retry from all configured DLQs

---

activemq-broker/src/main/java/org/apache/activemq/broker/region/virtual/VirtualTopicInterceptor.java
activemq-unit-tests/src/test/java/org/apache/activemq/broker/virtual/CustomVirtualTopicInterceptorWithLeadingWildcardTest.java

Checking for leading wildcard in the prefix for a virtualtopic, modifying the behavior of shouldDispatch in the VirtualTopicInterceptor.

AMQ-6310 added a check to ensure the leading wildcards in prefixes are handled correctly.

---

activemq-leveldb-store/readme.md

the wrong word in this sentence "with Hadoop based file systems to achive HA of your stored messages" .
“achive” change to "achieve".

fix a wrong word

---

activemq-karaf-itest/src/test/java/org/apache/activemq/karaf/itest/ActiveMQBrokerBlueprintTest.java
activemq-karaf-itest/src/test/resources/org/apache/activemq/karaf/itest/activemq-blueprint.xml

This pull request adds a test to create a broker using a blueprint.xml file.
This test also covers the xbean problem of the above issue as it uses a config attribute in a bean.

[AMQ-6514] Adding test for activemq blueprint setup and xbean problem

---

activemq-osgi/pom.xml
activemq-osgi/src/main/resources/META-INF/spring.schemas

As spring is embedded now we also need to define the spring schema mappings to make them available when being offline. Downside is that this needs to be maintained. So the better way would be to join the files from activemq-spring and spring. 
Does anyone know how to do this?

[AMQ-6544] Create spring.schemas with schemas of activemq and spring

---

activemq-broker/src/main/java/org/apache/activemq/broker/BrokerService.java
activemq-broker/src/test/java/org/apache/activemq/broker/BrokerServiceTest.java
activemq-camel/src/main/java/org/apache/activemq/camel/CamelShutdownHook.java
activemq-camel/src/test/java/org/apache/activemq/camel/BrokerPreShutdownHookTest.java

When Camel is run embedded within ActiveMQ it's shutdown is called at the point the broker is already stopped, this can lead to data loss as there could be exchanges that have not ended.
This adds the ability to specify preStopHook(s) that can be invoked during ActiveMQ shutdown but before the broker is shutdown.
With this Camel can gracefully shutdown while the broker is still started.

AMQ-6706 Allow for hooks before broker stop occurs

---

activemq-client/src/main/java/org/apache/activemq/filter/XPathExpression.java
activemq-console/src/main/java/org/apache/activemq/console/command/CreateCommand.java
activemq-runtime-config/src/main/java/org/apache/activemq/plugin/RuntimeConfigurationBroker.java

Good security practices say that all DocumentBuilderFactory instances should enable the secure processing feature and disable doctypes to avoid XXE attacks.

Enable secure processing on all DocumentBuilderFactory.newInstance()

---

activemq-web-console/src/main/webapp/WEB-INF/web.xml

We should disable directory listing for the web console, as a good security practise.

Disable directory listing for the webconsole

---

activemq-console/src/main/java/org/apache/activemq/console/command/CreateCommand.java

It's good security practice to set the secure processing feature on TransformerFactory instances (as well).

Set the secure processing feature on the TransformerFactory

---

activemq-camel/src/main/java/org/apache/activemq/camel/component/ActiveMQConfiguration.java

This is a trivial PR to make some class loading functionality private to ActiveMQConfiguration, as it's not used anywhere else.

Make ActiveMQConfiguration.loadClass private

---

activemq-broker/src/main/java/org/apache/activemq/security/LDAPAuthorizationMap.java
activemq-broker/src/main/java/org/apache/activemq/security/SimpleCachedLDAPAuthorizationMap.java
activemq-unit-tests/src/test/java/org/apache/activemq/security/CachedLDAPAuthorizationModuleLegacyTest.java
activemq-unit-tests/src/test/java/org/apache/activemq/security/CachedLDAPAuthorizationModuleTest.java
activemq-unit-tests/src/test/java/org/apache/activemq/security/LDAPAuthorizationMapTest.java
activemq-unit-tests/src/test/resources/org/apache/activemq/security/activemq-apacheds-legacy.xml
activemq-unit-tests/src/test/resources/org/apache/activemq/security/activemq-apacheds.xml

It's not good security practice to use default passwords.

Remove default "secret" password from the LDAPAuthorizationMap

---

activemq-http/src/main/java/org/apache/activemq/transport/http/HttpClientTransport.java

I reported and fixed AMQ-6949 roughly a year ago and have been running my fix without any issues ever since.

AMQ-6949: SocketTimeoutException when using HTTP transport connector

---

pom.xml

We should update Jackson databind to 2.9.9.3. Two new CVEs are issued for 2.9.9.2 (and a bug fix in 2.9.9.3):
https://www.cvedetails.com/cve/CVE-2019-14379
https://www.cvedetails.com/cve/CVE-2019-14439

AMQ-7266 - Update Jackson databind to 2.9.9.3

---

assembly/src/release/examples/openwire/ecommerce/src/Retailer.java

[AMQ-7199](https://issues.apache.org/jira/browse/AMQ-7199) For better control over randomness and comparatively less performance overhead, Random.nextDouble can be used instead of Math.random. Such a sample instance is showed in the attached commit.

[AMQ-7199] Replace Math.Random with Random.nextDouble

---

activemq-web-console/src/main/webapp/WEB-INF/web.xml
assembly/src/release/webapps/api/WEB-INF/web.xml

We should add the HTTPOnly flag to the webconsole + REST API Cookies

AMQ-7322 - Add HTTPOnly flag to the webconsole + REST API Cookies

---

doap.rdf

https://issues.apache.org/jira/browse/AMQ-7130 is caused by the fact that our doap JIRA link is incorrect. Once this PR is merged then https://projects.apache.org/project.html?activemq will need to be updated to point to git instead of svn.

AMQ-7130 Update AMQ doap

---

activemq-broker/src/main/java/org/apache/activemq/plugin/SubQueueSelectorCacheBroker.java

See details on https://issues.apache.org/jira/browse/AMQ-7312
On "browse" action in AMQ console, a consumer is added on related queue.
When virtualSelectorCacheBrokerPlugin is activated, "addConsumer" method add a 'TRUE' selector on that queue that disable previous cached selector.
Could you please merge that PR on next release ?

AMQ-7312 virtualSelectorCacheBrokerPlugin addConsumer issue

---

assembly/src/release/bin/activemq

If `JAVACMD` is set to `auto` (the default from the `env` file) and the current working directory contains a directory named `auto` (and the `auto` directory is executable, which directories normally are), the `activemq` init script will incorrectly detect the `auto` directory as the `java` binary thus leaving `JAVACMD` set to `auto` which is incorrect and will fail to execute the Java VM.
To fix this, in the second attempt to detect the `java` binary, repeat the tests for a zero-length `JAVACMD` or a `JAVACMD` equal to `auto` before testing whether `JAVACMD` does not exist or is not executable.  This is necessary because when the length of `JAVA_HOME` is zero, the first attempt to detect the location of the `java` binary will not set `JAVACMD` (so it will still be `auto` when it reaches …

Improve activemq init JAVACMD auto detection

---

pom.xml

Currently, the owasp plugin doesn't run correctly due to some system scope failures.

Update owasp plugin (and enable it to run correctly)

---

activemq-client/src/test/java/org/apache/activemq/broker/scheduler/CronParserTest.java

For the current implementation of CronParserTest, the "mvn clean package" is failing for me at CronParserTest.testgetNextTimeMinutes .
I've put a  Fix to Assert the nextMinute rather than converting to  seconds.

NO-JIRA: CronParserTest is failing in Indian StandardTime 

---

activemq-client/src/main/java/org/apache/activemq/ActiveMQConnection.java

Avoid calling toString() method in case of different log level, because toString() could create additional objects or could read volatile variable. For example:
org.apache.activemq.ActiveMQConnection#toString (AtomicBoolean)

AMQ-6963 Fix calling the toString() method in case of different log level.

---

activemq-web/src/main/java/org/apache/activemq/web/MessageQuery.java
activemq-web/src/main/java/org/apache/activemq/web/QueueBrowseQuery.java

`org.apache.activemq.web.controller.SendMessage` uses `org.apache.activemq.web.WebClient`, which can be configured to use console login credential instead of system user credential (by setting the connection factory username and password to `null`). This allows seamless per-user based authorization for operations through the web console. 
`org.apache.activemq.web.QueueBrowseQuery` was not using the `org.apache.activemq.web.WebClient` so it was impossible to setup authorization on per-user basis for browsing messages of a queue through web console. 
This change migrates `org.apache.activemq.web.QueueBrowseQuery` to use `org.apache.activemq.web.WebClient`.

AMQ-6908 Use WebClient in QueueBrowseQuery

---

activemq-broker/src/main/java/org/apache/activemq/plugin/SubQueueSelectorCacheBroker.java

Could this additional debug logging be considered for inclusion? The other debug logging in this class has proven to be helpful.

AMQ-7404 add debug logging for selectors loaded from the cache file

---

activemq-leveldb-store/pom.xml

Removing some old Tomcat dependencies. No JIRA created as it's just a change to test dependencies.

Remove unused activemq-leveldb test dependencies

---

activemq-broker/src/main/java/org/apache/activemq/broker/region/TopicRegion.java
activemq-stomp/src/main/java/org/apache/activemq/transport/stomp/ProtocolConverter.java

The error log message iss useless as the JMX exception is thrown and pollute the log. I'm using debug instead.

[AMQ-7347] Don't log error in case of topic subscription failure (use debug)

---

pom.xml

We should update Tomcat to 9.0.35 due to CVE-2020-9484

AMQ-7489 - Update Tomcat to 9.0.35

---

activemq-client/src/main/java/org/apache/activemq/transport/discovery/multicast/MulticastDiscoveryAgent.java

Guard against null return value from `java.net.NetworkInterface.getNetworkInterfaces()`.

Guard against null NetworkInterface.getNetworkInterfaces()

---

assembly/src/release/bin/env

This patch removes the shebang from the env file. The file is – and
should always be – sourced and never be executed directly and should
thus not contain a shebang.
The file has also already no executable flag. Probably for the same
reason.

Shebang in env

---

activemq-broker/src/main/java/org/apache/activemq/broker/BrokerService.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/DurableTopicSubscription.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/Topic.java
activemq-unit-tests/src/test/java/org/apache/activemq/usecases/ActiveDurableSubscriptionBrowseExpireTest.java

When an *active* durable subscription fails to acknowledge messages due to being offline/unreliable/misbehaved, messages which expire according to their TTL are not marked expired on that subscription. This can lead to an unbounded number of messages building up in the message store, eventually exhausting quotas and causing backpressure. This PR introduces a new broker-level setting `enableMessageExpirationOnActiveDurableSubs` which allows messages to expire on *active* durable subscriptions.
We have been running with this setting enabled in quite a few production environments for a couple of years with no observed ill effects. Even so, the new setting is disabled by default to ensure backward compatibility. This is my first attempt to submit a PR to this repo, so please let me know if I …

Adding an option which allows messages to expire on active durable subscriptions

---

activemq-broker/src/main/java/org/apache/activemq/broker/jmx/AnnotatedMBean.java
activemq-unit-tests/src/test/java/org/apache/activemq/broker/jmx/MBeanWithAuditLogTest.java

If audit log is turned on then Pause Queue doesn't work and causes `java.lang.NullPointerException`.
Steps to reproduce:
1. Start ActiveMQ normally with audit log turned on:
`./activemq start -Dorg.apache.activemq.audit=true`
2. Create a Queue normarlly: http://127.0.0.1:8161/admin/ > Queues > Enter Queue Name > Create 
3. Pause newly created queue: Click on `Pause`.
Extected result: Queue is paused normally.
Achieved result: 
- Error in web console:
Error!
Exception occurred while processing this request, check the log for more information!
- Error in the `activemq.log`:
```
2020-12-16 09:50:41,877 | INFO  | Starting Jetty server | org.apache.activemq.transport.WebTransportServerSupport | main
2020-12-16 09:50:41,992 | INFO  | Creating Jetty connector | …
```

[AMQ-8104] Tests and fixes NullPointerException when pause queue if audit log is turned on

---

activemq-shiro/src/main/java/org/apache/activemq/shiro/authz/ActiveMQWildcardPermission.java
activemq-shiro/src/test/java/org/apache/activemq/shiro/authz/ActiveMQWildcardPermissionTest.java

https://issues.apache.org/jira/browse/AMQ-8116
ActiveMQWildcardPermission with multiple tokens inconsistent with parent
WildcardPermission class
Update ActiveMQWildcardPermission.java
add testcase

AMQ-8116 ActiveMQWildcardPermission buggy

---

activemq-broker/src/main/java/org/apache/activemq/broker/TransportConnector.java
activemq-broker/src/main/java/org/apache/activemq/transport/auto/nio/AutoNIOSSLTransportServer.java
activemq-unit-tests/pom.xml
activemq-unit-tests/src/test/java/org/apache/activemq/transport/nio/NIOSSLBasicTest.java
activemq-unit-tests/src/test/java/org/apache/activemq/transport/nio/NIOSSLConcurrencyTest.java

Re-enable the nio transport tests in activemq-unit-tests by default to
catch transport errors. Also fix broken tests

AMQ-8184 - Re-enable NIO tests

---

pom.xml

The RAT plugin failed on `/docs/img/*.svg` when running `mvn apache-rat:check`

Fix Rat header check on logo files

---

activemq-client/src/main/java/org/apache/activemq/openwire/v1/BaseDataStreamMarshaller.java
activemq-client/src/main/java/org/apache/activemq/openwire/v10/BaseDataStreamMarshaller.java
activemq-client/src/test/java/org/apache/activemq/openwire/v1/BaseDataStreamMarshallerTest.java
activemq-client/src/test/java/org/apache/activemq/openwire/v10/BaseDataStreamMarshallerTest.java

AMQ-6894: Limit poison exception message to 1024 to avoid IOException be encoding

AMQ-6894: limit poison exception message to 1024

---

assembly/src/release/bin/activemq

According to the manual (and the `runlevel` command), Debian starts in runlevel 2 by default:
https://www.debian.org/doc/manuals/debian-reference/ch03.en.html#_sysv_style_init
So in order for ActiveMQ to start up when a Debian VM starts, you have to add it to these runlevels.
Workaround: `insserv -v activemq,start=2`
Side-effects:
RedHat doesn't use runlevels 2 and 4, so it should be fine:
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/3/html/Reference_Guide/s1-boot-init-shutdown-sysv.html
SLES doesn't use runlevel 4, but it does use runlevel 2 for "Local multiuser mode without remote network (NFS, etc.)":
https://www.suse.com/documentation/sles11/book_sle_admin/data/sec_boot_init.html
So the only side-effect on these systems is that SLES will try to run ActiveMQ …

Add missing runlevels to Default-Start

---

assembly/src/release/bin/activemq

The current version of the activemq start script uses options to ps which are unavailable 
in busybox.
Suggested change refactors the start script to remove duplicated code to find a java process 
given a pidfile and makes it work on busybox.
I have limited possibilities of verifying the change on different platforms but it is confirmed to
work on at least Mac OS X in addition to busybox and should work on platforms where 
previous "ps -p" command worked.

Make start script work on busybox

---

activemq-client/src/main/java/org/apache/activemq/thread/SchedulerTimerTask.java
activemq-client/src/test/java/org/apache/activemq/thread/SchedulerTest.java

Very interested to see whether this PR is considered to be useful...
At my current client, we came across the problem that for some reason (that we don't understand yet) a micro-service with a connection to the broker via the activemq-client would get in a state where every 5 seconds it would report a failure to connect to the broker with the reason being: _IllegalStateException: Timer already cancelled_.  
There are several examples on the internet of this problem occurring but I've not found an actual solution to the problem, or something that explains what the underlying cause is.
After much digging, I've come to think that the basic cause of the problem is in `java.util.Timer`.  Tasks controlled by a timer should never throw exceptions because, if they do, the timer then becomes …

Stop failed timer task from breaking timers.

---

activemq-client/pom.xml
activemq-client/src/main/java/org/apache/activemq/util/XStreamSupport.java
activemq-http/pom.xml
activemq-http/src/main/java/org/apache/activemq/transport/xstream/XStreamWireFormat.java
activemq-stomp/src/main/java/org/apache/activemq/transport/stomp/JmsFrameTranslator.java
activemq-stomp/src/test/java/org/apache/activemq/transport/stomp/util/XStreamBrokerContext.java

This PR moves `XStreamSupport` to `activemq-client`. 
Currently this sits in `activemq-stomp`, thus requiring the ActiveMQ HTTP client to require `activemq-stomp` module on its class path, even if the client isn't using stomp.

AMQ-7149 Remove dependency activemq-http and activemq-stomp

---

activemq-unit-tests/src/test/java/org/apache/activemq/usecases/DuplexAdvisoryRaceTest.java

- Fix flaky test `DuplexAdvisoryRaceTest` [AMQ-8190](https://issues.apache.org/jira/browse/AMQ-8190). 
- The test is flaky because time needed for received response greater than numMessagesPerDest * numDests is more than 10 min in CI env. [Failed example](https://github.com/charlie-cyf/activemq/runs/2181716367?check_suite_focus=true#step:9:2557)
This commit is tested on my local Github Actions: https://github.com/charlie-cyf/activemq/runs/2188672418?check_suite_focus=true#step:7:1223

AMQ-8190 add wait time & shrink duration for CI test run

---

activemq-unit-tests/src/test/java/org/apache/activemq/security/AbstractCachedLDAPAuthorizationMapLegacyTest.java

- This test is flaky because default 30s wait time is not enough for test run in CI env. [failed example](https://github.com/charlie-cyf/activemq/runs/2181716367?check_suite_focus=true#step:9:2214)
- changed wait time to maximum 5 min to fix this issue
Tested on my local Github Actions CI run: https://github.com/charlie-cyf/activemq/runs/2190121520?check_suite_focus=true#step:7:870

AMQ-8189 add wait time to CachedLDAPAuthorizationModuleTest

---

activemq-unit-tests/pom.xml
activemq-unit-tests/src/test/java/org/apache/activemq/broker/BrokerServiceTest.java
pom.xml

- BrokerServiceTest in `activemq-unit-tests` is failing because powermock 1.7.4 doesn't work with newly updated Mockito 3.8.0. [Error Message](https://github.com/Charlie-chenchrl/activemq/runs/2216193106?check_suite_focus=true#step:9:1533)
- BrokerServiceTest used powermock to mock static functions, since Mockito start to support static mocks from 3.4.0 and this is the only place we use powermock, we can replace powermock with Mockito
- run `mvn clean test -Dtest=BrokerServiceTest`, test result in local CI: https://github.com/Charlie-chenchrl/activemq/runs/2216276748?check_suite_focus=true#step:7:195 (line 195)

fix BrokerServiceTest by replacing powermock

---

activemq-karaf/src/main/resources/features-core.xml
activemq-karaf/src/main/resources/features.xml

Installing activemq feature can cause several refresh. The user should use spring-legacy from Karaf version instead of the range.

[AMQ-8218] Installing activemq features breaks http commands

---

activemq-client/src/main/java/org/apache/activemq/command/ActiveMQMessage.java

ActiveMQMessage.getStringProperty() should exchange equals method call objects,
and let `ActiveMQMessage.getObjectProperty()` do not null check, thanks

[AMQ-8350] ActiveMQMessage.getStringProperty() should exchange equals method call objects

---

pom.xml

A dependency bot recommended bumping this version. No breaking changes.
I see no reason why not :)

upgrade jaxb-basics-version to 0.12.0

---

activemq-broker/src/main/java/org/apache/activemq/broker/TransportConnection.java
activemq-broker/src/main/java/org/apache/activemq/broker/TransportConnector.java

Introduce stackTraceEnabled flag on transport connector define if the stack trace should be displayed or not in case of WARN messages

[AMQ-8252] Introduce stackTraceEnabled flag on transport connector

---

activemq-broker/src/main/java/org/apache/activemq/broker/jmx/DestinationView.java
activemq-broker/src/main/java/org/apache/activemq/broker/jmx/DestinationViewMBean.java
activemq-unit-tests/src/test/java/org/apache/activemq/broker/jmx/MBeanTest.java

It is possible today through functionality of ```sendTextMessageWithProperties(...)``` to send a 
```TextMessage``` with jconsole containing properties. 
Input ```body=Hello World!,JMSCorrelationID=MyCorrId``` will result in message:
Given input of ```body=Hello, World!,JMSCorrelationID=MyCorrId``` we expect message body 
to contain Hello, World! and correlation id be set. Instead it will result in message:
I work with applications using in-memory brokers for development. It´s not uncommon for me to have to manually send
a text message to trigger a listener. The messages I send often include comma in the body, for example a json or a csv.
This PR enables possibility to provide own delimiter to the operation.
Given input of ```body=Hello, World!;JMSCorrelationID=MyCorrId``` and delimiter …

[AMQ-8372] Allow custom delimiter when sending TextMessages via MBean

---

activemq-client/src/main/java/org/apache/activemq/ActiveMQConnection.java

- Store maxFrameSize on client-side
- Check messages on outbound send to send an actionable exception to the caller
- Oversized messages are never sent to the broker!

[AMQ-8412] Client-side handling of max frame size received from broker

---

activemq-broker/src/main/java/org/apache/activemq/broker/region/Topic.java
activemq-broker/src/main/java/org/apache/activemq/plugin/StatisticsBroker.java
activemq-partition/src/test/java/org/apache/activemq/partition/PartitionBrokerTest.java
activemq-unit-tests/src/test/java/org/apache/activemq/plugin/BrokerStatisticsPluginTest.java

_(To main branch)_
Adding a feature (STATS_FIRST_MESSAGE_TIMESTAMP) to the StatisticsBrokerPlugin's destination-statistics for getting the
timestamp of the first message in the destination(s) being requested: If you on the query-message set the property StatisticsBroker.STATS_FIRST_MESSAGE_TIMESTAMP to anything (e.g. boolean true), a long value "firstMessageTimestamp" will be added to the statistics reply message(s). Since the reply message has JMSTimestamp set, which is the broker's now-timestamp, you may also on the query side calculate the age of the first message in milliseconds. The key name was chosen since that is the name of the corresponding feature in Artemis.
This extension of the existing feature is implemented to be as non-intrusive as possible, adding very little runtime …

StatisticsBrokerPlugin: Add feature: request destination firstMessageTimestamp

---

pom.xml

5.16.x must be built with Java 8. Main requires Java 11+. Many people just have Java 11 defaults now regardless.
This enforces the restriction to make it fail quickly+obviously to aid during mismatches or slips when switching back and forth.

AMQ-8488: fail 5.16.x build quickly+obviously if not run on Java 8

---

activemq-itests-spring31/pom.xml
activemq-karaf-itest/pom.xml
activemq-osgi/pom.xml
activemq-tooling/activemq-perf-maven-plugin/pom.xml
activemq-unit-tests/pom.xml
pom.xml

Updates the modules part of the previous full.test profile to always
build but skip running tests by default.
Also fixed miss dependency updates including log4j and jetty

AMQ-8520: Re-enable all modules to compile and build by default

---

assembly/src/release/bin/env

since the last release , the xmx and xms are hardcoded on `env` , the goal is to use ACTIVEMQ_OPTS_MEMORY environement variable if needed to override memory options

add the capability to override memory options

---

activemq-unit-tests/pom.xml
activemq-unit-tests/src/test/java/org/apache/activemq/broker/BrokerRedeliveryTest.java
activemq-unit-tests/src/test/java/org/apache/activemq/bugs/AMQ3537Test.java
activemq-unit-tests/src/test/java/org/apache/activemq/bugs/AMQ4952Test.java
activemq-unit-tests/src/test/java/org/apache/activemq/network/DurableFiveBrokerNetworkBridgeTest.java
activemq-unit-tests/src/test/java/org/apache/activemq/store/jdbc/JDBCConcurrentDLQTest.java
activemq-unit-tests/src/test/java/org/apache/activemq/usecases/OfflineDurableSubscriberTimeoutTest.java
activemq-unit-tests/src/test/resources/spring-embedded-xbean-local.xml
activemq-unit-tests/src/test/resources/spring-embedded-xbean.xml
activemq-unit-tests/src/test/resources/spring-embedded.xml
activemq-unit-tests/src/test/resources/spring-queue.xml
activemq-unit-tests/src/test/resources/spring.xml

**Broken Tests Fixed by this PR:**
**Broken Tests already fixed in main: (JMS 2.0, only applies to 5.18.x so don't need to backport)**
**Broken Tests already fixed in another PR:**
The issue is Spring 5.3 seems to require an updated annotation spec. geronimo-annotation_1.0_spec is too old. However, it's broken due to @Resource annotation usage which we only used in a couple unit tests. The jar is marked as optional and it's never used anywhere in the real codebase so the broker will run out of the box just fine. I think we can just fix/update this in 5.17.1 and 5.18.0 because if someone is using that annotation in their own code and Spring 5.3 they can just make sure to include the right annotation jar (spring already pulls it in) so they really just need to add an exclusion on the …

AMQ-8528: Fix test failures in integration module

---

activemq-client/src/main/java/org/apache/activemq/ActiveMQSslConnectionFactory.java
activemq-unit-tests/src/test/java/org/apache/activemq/ActiveMQSslConnectionFactoryTest.java

Inside ActiveMQSslConnectionFactory the passwords should be checked for
null so a NPE isn't thrown. Null will be passed to the factories instead
and the keystore/truststore factories will try and load the keystores
using null for the password which may or may not work depending on the
implementation and if password is set.

AMQ-8550 - Check for null keystore/truststore passwords

---

pom.xml

This PR updates the Spring Framework version used in ActiveMQ to 5.3.18.

Update Spring to 5.3.18.

---

activemq-web/src/main/java/org/apache/activemq/web/BrokerFacadeSupport.java
activemq-web/src/test/java/org/apache/activemq/web/BrokerFacadeSupportTest.java

Quoted values fixed the exception when a destination includes a colon but actually broke finding destination mbeans in general. With this change, the console will show active consumers and also supports queues with a colon 👍

[AMQ-8597] Show active consumers in web console

---

activemq-broker/pom.xml
activemq-kahadb-store/pom.xml
activemq-mqtt/pom.xml
activemq-rar/pom.xml
activemq-unit-tests/pom.xml
pom.xml

https://issues.apache.org/jira/browse/AMQ-9005
There's no use of Xalan in code and all tests are passing without the dependency. Seems safe to remove but I assume we'll need a note about it in the release notes.

[AMQ-9005] remove xalan dependency due to it being end of life

---

activemq-broker/pom.xml
activemq-client/pom.xml
activemq-unit-tests/pom.xml
pom.xml

use -noindex to remove various .js files, disable html source listings for javadoc
https://issues.apache.org/jira/browse/AMQ-9074

AMQ-9074: javadoc output simplifications

---

activemq-jaas/src/main/java/org/apache/activemq/jaas/LDAPLoginModule.java

Re-using LDAP context for authentication. The context is created only once and re-used each time ActiveMQ server established connection with ActiveMQ clients.
Refactoring some code in LDAPLoginModule.java
This PR is based on fix introduced to Artemis: https://github.com/apache/activemq-artemis/commit/f3a8619d7eeabded75f3725f2e77af267e8cb450#diff-706fd9b54d2aed5a0ea5d28fa7c70f7ee733672f7e91d847137517e3b147d716
Manual test authentication using LDAP
https://issues.apache.org/jira/browse/AMQ-6148

AMQ-6148 Reusing LDAP context to avoid creating new connections

---

activemq-broker/src/main/java/org/apache/activemq/broker/region/Queue.java
activemq-unit-tests/src/test/java/org/apache/activemq/advisory/AdvisoryTests.java

Due to changes with Queues to check if consumers are full before adding more messages to the subscription, the Queue dispatch logic needed to be updated to mark subscriptions as slow and send advisories if configured instead of relying on the subscription itself to do it.

AMQ-9153: Fix slow consumer advisory for queue subscriptions

---

activemq-broker/src/main/java/org/apache/activemq/broker/jmx/ManagedRegionBroker.java
activemq-unit-tests/src/test/java/org/apache/activemq/broker/jmx/JmxConsumerRemovalTest.java

This new approach just looks matching Subscriptions from the region for the destination which prevents having to store another map and falls back to the old approach if something went wrong.

AMQ-9107 - rework performance improvement for consumer closing in managed region broker

---

activemq-unit-tests/pom.xml

Since enabling more tests in AMQ-9152 all the runs keep timing out with the same error of "There was a timeout in the fork". Attempting to increase the timeout to see if that works otherwise we will have to try and figure out the specific test causing the issue.
This isn't meant to be merged yet, it's just being pushed so tests can run.

No Jira: forkedProcessTimeoutInSeconds

---

activemq-karaf-itest/pom.xml
activemq-ra/pom.xml
activemq-runtime-config/pom.xml
activemq-spring/pom.xml
pom.xml

this won't fix every issue, but improve the situation
see https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/activemq/README.md

improve Reproducible Builds

---

Jenkinsfile

This should help reduce failures from flaky tests and make the build more reliable

NO-JIRA - Set tests to rerun failing tests 2 times

---

activemq-broker/src/main/java/org/apache/activemq/broker/region/Queue.java
activemq-kahadb-store/src/main/java/org/apache/activemq/store/kahadb/MessageDatabase.java
activemq-runtime-config/src/main/java/org/apache/activemq/plugin/AbstractRuntimeConfigurationBroker.java

This is best practice and will prevent unlock from being attempted inside of a finally block when the thread doesn't actually own the lock which can happen when the lock attempt throws an exception such as calling lockInterruptibly()

AMQ-9202 - Make sure Reentrant locks are acquired outside a try block

---

activemq-broker/src/main/java/org/apache/activemq/util/IOHelper.java
activemq-kahadb-store/src/test/java/org/apache/activemq/store/kahadb/MessageDatabaseTest.java

A store directory is created by `MessageDatabase.getPageFile()` which is called in two cases:
1. `KahaDBStore.start()` when creating a queue
2. `KahaDBStore.size()` which is performed when sending any persistent message
If both methods are called concurrently it's possible to get an IOException thrown from the `IOHelper.mkdirs()` method.

[AMQ-9199] Fixed race condition in creating store directory

---

pom.xml

[INFO]   maven-antrun-plugin ................................ 3.0.0 -> 3.1.0
[INFO]   maven-assembly-plugin .............................. 3.3.0 -> 3.4.2
[INFO]   maven-enforcer-plugin .............................. 3.1.0 -> 3.2.1
[INFO]   maven-jar-plugin ................................... 3.2.2 -> 3.3.0
[INFO]   maven-javadoc-plugin ............................... 3.3.2 -> 3.4.1
[INFO]   maven-plugin-plugin ................................ 3.6.4 -> 3.7.1
[INFO]   maven-project-info-reports-plugin .................. 3.4.0 -> 3.4.2
[INFO]   maven-release-plugin ......................... 3.0.0-M5 -> 3.0.0-M7
[INFO]   maven-surefire-plugin ........................ 3.0.0-M6 -> 3.0.0-M8
[INFO]   org.apache.rat:apache-rat-plugin ..................... 0.13 -> 0.15
[INFO] …

[AMQ-9203] Upgrade various maven plugins

---

activemq-client/src/main/grammar/SelectorParser.jj
pom.xml

Build warnings that need review
```
Reading from file activemq/activemq-client/src/main/grammar/SelectorParser.jj . . .
Warning: Line 22, Column 3: Command line setting of "STATIC" modifies option value in file.
Warning: Line 23, Column 3: Command line setting of "UNICODE_INPUT" modifies option value in file.
Warning: Line 26, Column 3: Command line setting of "ERROR_REPORTING" modifies option value in file.
File "TokenMgrError.java" does not exist.  Will create one.
File "ParseException.java" does not exist.  Will create one.
File "Token.java" does not exist.  Will create one.
File "SimpleCharStream.java" does not exist.  Will create one.
Parser generated with 0 errors and 3 warnings.
```

[AMQ-9058] Upgrade javacc-maven-plugin to 3.0.1

---

activemq-rar/pom.xml
activemq-unit-tests/pom.xml
pom.xml

Dependency updates:
com.thoughtworks.xstream:xstream .................... 1.4.19 -> 1.4.20 
commons-daemon:commons-daemon ......................... 1.3.2 -> 1.3.3 
org.apache.ant:ant ................................ 1.10.12 -> 1.10.13 
org.apache.shiro:shiro-core ......................... 1.10.1 -> 1.11.0 
org.apache.shiro:shiro-spring ....................... 1.10.1 -> 1.11.0 
org.codehaus.jettison:jettison ........................ 1.5.2 -> 1.5.3 
regexp:regexp ............................................. 1.3 -> 1.5 
org.apache.httpcomponents:httpclient ................ 4.5.13 -> 4.5.14 
org.apache.httpcomponents:httpcore .................. 4.4.15 -> 4.4.16

[AMQ-9207] Upgrade various dependencies

---

activemq-client/src/main/java/org/apache/activemq/ActiveMQConnection.java
activemq-unit-tests/src/test/java/org/apache/activemq/jms2/ActiveMQJMS2ConnectionTest.java

Adds a real implemention for createSession() and createSession(ackMode) methods on ActiveMQConnection

AMQ-7309 - Implement JMS 2.0 createSession methods

---

activemq-broker/src/main/java/org/apache/activemq/broker/region/policy/AbstractDeadLetterStrategy.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/policy/IndividualDeadLetterStrategy.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/policy/SharedDeadLetterStrategy.java

This fixes the rollback on message audit when retrying messages after the latest changes by using the originalDestination property to look up the correct message audit on rollback

AMQ-9217 - Fix IndividualDeadLetter strategy when retrying messages

---

activemq-client/src/main/java/org/apache/activemq/ActiveMQProducer.java
activemq-client/src/main/java/org/apache/activemq/command/ActiveMQBytesMessage.java
activemq-client/src/main/java/org/apache/activemq/command/ActiveMQMapMessage.java
activemq-client/src/main/java/org/apache/activemq/command/ActiveMQMessage.java
activemq-client/src/main/java/org/apache/activemq/command/ActiveMQObjectMessage.java
activemq-client/src/main/java/org/apache/activemq/command/ActiveMQStreamMessage.java
activemq-client/src/main/java/org/apache/activemq/command/ActiveMQTextMessage.java
activemq-client/src/main/java/org/apache/activemq/util/ByteSequence.java
activemq-unit-tests/src/test/java/org/apache/activemq/jms2/ActiveMQJMS2MessageTest.java

This might still need some tweaks but there's some initial tests pushed and wanted to get eyes on it and any feedback.

AMQ-7309 - Implement Message#isBodyAssignableTo and Message#getBody methods

---

activemq-broker/src/main/java/org/apache/activemq/network/NetworkBridgeConfiguration.java
activemq-unit-tests/src/test/java/org/apache/activemq/network/MQTTNetworkOfBrokersFailoverTest.java
activemq-unit-tests/src/test/java/org/apache/activemq/network/NetworkConnectorDefaultsTest.java

[AMQ-5137] make networkConnector decreaseNetworkConsumerPriority="true" the default

---

activemq-jdbc-store/src/main/java/org/apache/activemq/store/journal/JournalPersistenceAdapter.java
activemq-jdbc-store/src/main/java/org/apache/activemq/store/journal/JournalPersistenceAdapterFactory.java

[AMQ-9161] Mark JDBC JournalPersistenceAdapter as deprecated for removal

---

activemq-jdbc-store/src/main/java/org/apache/activemq/store/journal/JournalPersistenceAdapter.java
activemq-jdbc-store/src/main/java/org/apache/activemq/store/journal/JournalPersistenceAdapterFactory.java

The previous comment added in PR #989 added a second javadoc comment which prevent Xbean from generating the correct schema

AMQ-9161 - Fix javadoc comment so Xbean parsing works

---

activemq-web-console/pom.xml
activemq-web-demo/src/test/java/org/apache/activemq/web/RestTest.java
activemq-web/pom.xml
activemq-web/src/main/java/org/apache/activemq/web/AjaxListener.java
activemq-web/src/main/java/org/apache/activemq/web/MessageListenerServlet.java
activemq-web/src/main/java/org/apache/activemq/web/MessageServlet.java
activemq-web/src/main/java/org/apache/activemq/web/async/AsyncServletRequest.java

This commit removes the dependency on jetty-continuation and updates the MessageServlet and AjaxListener servlets to use the Servlet Async api directly for async requests through a new Async holder object that is used to track/manage the request.
As I mentioned in the Jira, this is also fine to backport to 5.18.x as there's no public facing API changes, it's just an internal detail. Jetty was already using the Async api and we are doing the same, just more directly now.
The tests in the activemq-web-demo can be run to test out and demonstrate the new changes. Running the [AjaxTest](https://github.com/cshannon/activemq/blob/6a979685c6a7d5cb6a091cb85e42bd03093adfa4/activemq-web-demo/src/test/java/org/apache/activemq/web/AjaxTest.java) in that project shows the AjaxListener still works with …

AMQ-9243 - Remove deprecated jetty-continuation dependency

---

pom.xml

last release was not fully reproducible: https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/activemq/README.md
one issue was https://issues.apache.org/jira/browse/FELIX-6602, fixed with maven-bundle-plugin 5.1.9
other issue remains to be studied and fixed: perhaps it's due to https://issues.apache.org/jira/browse/MNG-7750, which would mean that using Maven 3.9.2 would be necessary to have a Reproducible Build

upgrade m-bundl-p: fixes RB issue

---

activemq-broker/src/main/java/org/apache/activemq/network/DemandForwardingBridgeSupport.java
activemq-unit-tests/src/test/java/org/apache/activemq/network/CompositeConsumerNetworkBridgeTest.java
activemq-unit-tests/src/test/java/org/apache/activemq/network/DurableSyncNetworkBridgeTest.java
activemq-unit-tests/src/test/java/org/apache/activemq/network/DynamicNetworkTestSupport.java
activemq-unit-tests/src/test/java/org/apache/activemq/network/ForceDurableNetworkBridgeTest.java

This fixes network subscriptions that are generated on demand when a consumer uses composite destinations. Before this fix conduit subscriptions didn't work correctly. This fix now splits up the composite dest and generates correct demand for each of the individual destinations.

AMQ-9262 - Fix network subscriptions for composite consumers

---

assembly/src/release/bin/activemq

When ActiveMQ is started the following is printed out: "INFO: Starting - inspect logfiles specified in logging.properties and log4j.properties to get details" No log4j.properties file exists, there is however, log4j2.properties.

[AMQ-9285] On startup inform to inpsect log4j2.properties

---

activemq-web-demo/src/main/webapp/WEB-INF/web.xml
assembly/src/release/webapps/api/WEB-INF/web.xml

Related to https://issues.apache.org/jira/browse/AMQ-8611
A message size limit has been added when sending messages over REST but it is not yet documented.
* Add a comment with an example of `maxMessageSize` configuration to all existing configurations of `MessageServlet`

[AMQ-8611] Describe message size limit init parameter

---

activemq-client/src/main/java/org/apache/activemq/command/ActiveMQMapMessage.java
activemq-client/src/main/java/org/apache/activemq/command/Message.java
activemq-http/src/test/java/org/apache/activemq/bugs/AMQ9255Test.java

Fixes https://issues.apache.org/jira/browse/AMQ-9255
Persistent messages with an expired TTL are not moved to the DLQ when the HTTP protocol is used as transport. 
* Initialize the field `Message#processAsExpired` at deserialization
* Add a unit test to reproduce the bug

[AMQ-9255] Initialize the transient field of the class Message

---

activemq-http/src/webapp/WEB-INF/web.xml
activemq-web-console/src/main/webapp/WEB-INF/web.xml
activemq-web-demo/src/main/webapp/WEB-INF/web.xml
assembly/src/release/webapps/api/WEB-INF/web.xml

The schema location of the Jakarta namespace is not properly set which prevents the auto-completion in IDEs
* Fix the schema location of the Jakarta namespace in all the web.xml files that have the same problem

Fix the schema location in web.xml files

---

assembly/src/docker/Dockerfile

Fixes https://issues.apache.org/jira/browse/AMQ-9306
Due to [AMQ-7007](https://issues.apache.org/jira/browse/AMQ-7007), the WebConsole is not accessible from outside a Docker container so even if a port is opened on the host to access the WebConsole, an empty response is returned whatever the HTTP request sent.
* Set `0.0.0.0` as Jetty host to make the WebConsole accessible

[AMQ-9306] Make the WebConsole accessible from outside the container

---

assembly/src/docker/Dockerfile
assembly/src/docker/README.md
assembly/src/docker/build.sh

Fixes https://issues.apache.org/jira/browse/AMQ-9305
The Dockerfile and corresponding README need to be adapted to Java 17 in order to be able to launch a snapshot of ActiveMQ 5.19 inside a Docker container.
* Use `eclipse-temurin:17-jre` as new root image
* Modify the documentation to refer to the new root image used

[AMQ-9305] Adapt the docker-related files to Java 17

---

activemq-broker/src/main/java/org/apache/activemq/broker/TransportConnection.java

In TransportConnection.java:861, the synchronized list returned by cs.getTempDestinations() is iterated
in an unsynchronized manner, but according to the [Oracle Java 7 API specification](http://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#synchronizedList%28java.util.List%29),
this is not thread-safe and can lead to non-deterministic behavior. This pull request adds a fix by synchronizing the iteration on the list returned by cs.getTempDestinations().

TransportConnection does not synchronize iteration on synchronized list

---

activemq-kahadb-store/src/main/java/org/apache/activemq/store/kahadb/KahaDBStore.java
activemq-unit-tests/src/test/java/org/apache/activemq/store/kahadb/KahaDBInFlightTxMemoryUsageTest.java

This commit will reduce the memory required in KahaDB for long running transactions and transactions with a lot of pending message sends by clearing out the message memory when no longer needed instead of keeping it tracked in the pending map

AMQ-9343 - Reduce memory used for in flight transactions

---

assembly/pom.xml

The current version of camel pulls in the activemq-client-jakarta jar which is not necessary as it no longer exists with ActiveMQ 6.0.0
Furthermore the version being pulled in is 5.18.2 which contains a critical CVE that was fixed in 5.18.3

AMQ-9388 - Exclude activemq-client-jakarta from camel-activemq

---

activemq-client-jakarta/pom.xml
activemq-client/src/main/java/org/apache/activemq/openwire/OpenWireUtil.java
activemq-client/src/main/java/org/apache/activemq/openwire/v12/BaseDataStreamMarshaller.java

This fixes the OpenWire v12 marshaller so that if an exception is received by a jakarta based broker the client will convert back to a javax jms exception type.
This commit also updates activemq-client-jakarta to do the proper mapping in the reverse.

AMQ-9418 - Support converting jakarta jms exceptions to javax

---

activemq-client/src/main/java/org/apache/activemq/openwire/OpenWireUtil.java
activemq-client/src/main/java/org/apache/activemq/openwire/v12/BaseDataStreamMarshaller.java

This fixes the OpenWire v12 marshaller so that if an exception is received by a javax based broker the client will convert back to a jakarta jms exception type.

AMQ-9418 - Support converting javax jms exceptions to jakarta

---

activemq-kahadb-store/src/main/java/org/apache/activemq/store/kahadb/MessageDatabase.java
activemq-unit-tests/src/test/java/org/apache/activemq/store/kahadb/KahaDBDurableMessageRecoveryTest.java

This commit fixes a bug in KahaDB that caused gaps in sequence ack tracking for durables that would lead to the appearance of stuck messages on durable subs if duplicate messages were detected. The sequence is now correctly rolled back so that there is no gap if the message is not added to the order index

AMQ-9435 - Ensure orderIndex next id is rolled back on duplicates

---

activemq-broker/src/main/java/org/apache/activemq/broker/region/cursors/StoreQueueCursor.java
activemq-unit-tests/src/test/java/org/apache/activemq/broker/region/QueueDuplicatesFromStoreTest.java

This commit fixes the initialization of the StoreQueueCursor message audit object to make sure it's shared between the persistent and non persistent cursors. It also adds a check to ensure that duplicate calls to start will not try and init more than once.

AMQ-9436 - Ensure message audit in queue store cursor is shared

---

activemq-broker/src/main/java/org/apache/activemq/plugin/StatisticsBroker.java
activemq-unit-tests/src/test/java/org/apache/activemq/plugin/BrokerStatisticsPluginTest.java

When dest is instance of DestinationFilter the queue/topic message is not accessed (statistic "firstMessageTimestamp" is not sent)

AMQ-9452: unwind BaseDestination to access queue/topic message

---

activemq-broker/src/main/java/org/apache/activemq/broker/jmx/Log4JConfigView.java

The Current The Log4jConfiguration's JMX method to reload the log4j properties i.e **reloadLog4jProperties**  yield NoSuchMethodException.
As the method resetConfiguration no longer exists, in LogManager.
Have Updated the Methods to be called to trigger the reload properly.

[AMQ-9470] Updated Methods to be called, to properly reload Log4j Properties

---

assembly/pom.xml

The jrms-1.1 library has not seen any releases/updates since 2005 and [Maven](https://mvnrepository.com/artifact/jrms/jrms/usages) lists only ActiveMQ and Apache Camel as upstream usages.
After digging through ActiveMQ's mailing lists and commit history, I found that it [used to be listed](https://github.com/apache/activemq-web/blob/7a7d976c/2004/06/23/jgroups-and-jrms-support.xml) on ActiveMQ's [URI Protocols](https://activemq.apache.org/components/classic/documentation/uri-protocols) page, but was removed at some point. JRMS seems to be listed as a peer-to-peer option on the [topologies](https://activemq.apache.org/components/classic/documentation/topologies) page but is not discussed in either the [peer](https://activemq.apache.org/components/classic/documentation/peer-transport-referen …

[AMQ-9469] Removed JRMS-1.1 dependency from assembly pom.xml

---

activemq-broker/src/main/java/org/apache/activemq/broker/region/AbstractRegion.java
activemq-unit-tests/src/test/java/org/apache/activemq/bugs/AMQ9475Test.java

This fixes an issue where wildcard destinations could be inadvertently created by ConsumerControl commands which could lead to problems. The processing logic for this command now will only look up existing destinations if they exist.

AMQ-9475 - ConsumerControl commands should not auto create wildcard dests

---

activemq-web-demo/src/test/java/org/apache/activemq/web/RestTest.java
activemq-web/src/main/java/org/apache/activemq/web/async/AsyncServletRequest.java

Previously a timeout was thrown and complete was not called so Jetty was returning a 500 error

AMQ-9330 - Return 204 code when polling empty destinations

---

activemq-broker/src/main/java/org/apache/activemq/broker/region/BaseDestination.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/Queue.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/Topic.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/policy/ChainMessageInterceptorStrategy.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/policy/HeaderMessageInterceptorStrategy.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/policy/MessageInterceptorStrategy.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/policy/PolicyEntry.java
activemq-unit-tests/src/test/java/org/apache/activemq/broker/policy/MessageInterceptorStrategyMemoryUsageTest.java
activemq-unit-tests/src/test/java/org/apache/activemq/broker/policy/MessageInterceptorStrategyTest.java

Documentation notes:
1. Note about scenario of vm:// transport and disabling copyMessageOnSend and mutability/thread race issue

[AMQ-9455] DestinationPolicy support for MessageInterceptorStrategy

---

activemq-broker/src/main/java/org/apache/activemq/broker/TransportConnection.java

Iteration over collections or arrays  can be replaced with an enhanced for loop (foreach iteration syntax). 
```
The for-each construct gets rid of the clutter and the opportunity for error.
When should you use the for-each loop? Any time you can. It really beautifies your code.
```
See more details why : https://docs.oracle.com/javase/8/docs/technotes/guides/language/foreach.html

for loop can be replaced with enhanced for

---

activemq-kahadb-store/src/main/java/org/apache/activemq/store/kahadb/disk/page/PageFile.java
activemq-kahadb-store/src/main/java/org/apache/activemq/util/RecoverableRandomAccessFile.java
activemq-kahadb-store/src/test/java/org/apache/activemq/store/kahadb/disk/page/PageFileTest.java

This method always throws an exception so it should be removed and no longer used. Places in `PageFile` that called the method have been updated to either remove the usage or throw an error.
Update: I was able to add a test in `PageFileTest` to verify there's no more exception if the recovery file is missing as the page file no longer calls setLength() and will continue

AMQ-9547 - Remove setLength() and usage from RecoverableRandomAccessFile

---

activemq-stomp/src/test/java/org/apache/activemq/transport/stomp/StompNIOSSLLargeMessageTest.java

CI build started failing after https://github.com/apache/activemq/pull/1290 had been merged:
* this PR - https://ci-builds.apache.org/job/ActiveMQ/job/ActiveMQ/job/PR-1290/2/cloudbees-pipeline-explorer/#line-12002
* 5.18.x - https://ci-builds.apache.org/job/ActiveMQ/job/ActiveMQ/job/activemq-5.18.x/141/cloudbees-pipeline-explorer/#line-12166
* 6.11.x - https://ci-builds.apache.org/job/ActiveMQ/job/ActiveMQ/job/activemq-6.1.x/14/cloudbees-pipeline-explorer/#line-11963
* main - https://ci-builds.apache.org/job/ActiveMQ/job/ActiveMQ/job/main/482/cloudbees-pipeline-explorer/#line-11996
However, after some local troubleshooting, I believe the problem is not particularly related to those changes. The root cause seems to be related to a missing tear down logic in one of tests.

AMQ-8398 - Add missing super.tearDown() call to Stomp NIOSSLLargeMessageTest

---

assembly/src/release/conf/jetty.xml

Unspecified Cache-Control HTTP header is vulnerable. Set it to no-store to avoid caching sensitive data for stronger security. It should be the default unless users override it.
Reference: https://www.virtuesecurity.com/kb/cache-controls-explained/
> Note: this PR was approved at https://github.com/apache/activemq/pull/1238 However, the branch history for that PR was messed up due to wrong operation with git. I closed that one and opened a new one (this one). Please approve again, thank you so much.

 [AMQ-9545] Set cache-control to no-store by default for stronger security

---

activemq-client/src/main/java/org/apache/activemq/util/DataByteArrayOutputStream.java
activemq-client/src/test/java/org/apache/activemq/util/DataByteArrayInputStreamTest.java
activemq-kahadb-store/src/main/java/org/apache/activemq/store/kahadb/disk/util/DataByteArrayOutputStream.java

As a part of https://github.com/apache/activemq/pull/1284, I re-wrote `DataByteArrayInputStreamTest`. Since we decided to take another route for the fix and closed that PR, I'd like to merge these changes separately.
This PR addresses problems mentioned in https://issues.apache.org/jira/browse/AMQ-8122.

AMQ-8122 - Fix DataByteArrayInputStreamTest

---

activemq-broker/src/main/java/org/apache/activemq/broker/TransactionBroker.java
activemq-broker/src/main/java/org/apache/activemq/broker/jmx/DestinationView.java
activemq-broker/src/main/java/org/apache/activemq/broker/jmx/DestinationViewMBean.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/BaseDestination.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/Destination.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/DestinationFilter.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/DestinationStatistics.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/DurableTopicSubscription.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/Queue.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/Topic.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/TopicSubscription.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/policy/PolicyEntry.java
activemq-runtime-config/src/test/java/org/apache/activemq/PolicyEntryTest.java
activemq-runtime-config/src/test/resources/org/apache/activemq/policyEntryTest-policy-advancedNetworkStatistics-mod.xml
activemq-runtime-config/src/test/resources/org/apache/activemq/policyEntryTest-policy-advancedNetworkStatistics.xml
activemq-unit-tests/src/test/java/org/apache/activemq/network/NetworkAdvancedStatisticsTest.java
activemq-unit-tests/src/test/resources/org/apache/activemq/network/localBroker-advancedNetworkStatistics.xml
activemq-unit-tests/src/test/resources/org/apache/activemq/network/remoteBroker-advancedNetworkStatistics.xml

replaces bad no-squash merge that was reverted: https://github.com/apache/activemq/pull/1156

[AMQ-9437] AdvancedDestination statistics networkEnqueue and networkDequeue counters

---

activemq-broker/src/main/java/org/apache/activemq/broker/jmx/AnnotatedMBean.java
activemq-client/src/main/java/org/apache/activemq/ActiveMQConnectionFactory.java

[AMQ-9563] JDK 21 support: Remove usage of java.security.AccessController from ActiveMQConnectionFactory

---

activemq-client/src/main/java/org/apache/activemq/util/ProducerThread.java
activemq-console/src/main/java/org/apache/activemq/console/command/ProducerCommand.java
activemq-console/src/main/resources/org/apache/activemq/console/command/producer.txt

Jira tickets: https://issues.apache.org/jira/projects/AMQ/issues/AMQ-9596?filter=allissues

[AMQ-9596] Add priority and disableMessageTimestamp to the producer command

---

activemq-kahadb-store/src/main/java/org/apache/activemq/store/kahadb/KahaDBStore.java
activemq-unit-tests/src/test/java/org/apache/activemq/usecases/DurableSubscriptionPartialAckTest.java

**What problems does this PR solve?**
Fixes a bug when a durable consumer can received messages which it's already acknowledged
**Why is it beneficial to merge into ActiveMQ?**
It fixes a bug
**How do you make sure this PR is well tested?**
I couldn't find any tests that test that part of code directly. I wrote a higher level test that covers that edge case.

[AMQ-9595] Fix recoverNextMessages when there are messages consumed farther than maxBatchSize.

---

activemq-broker/src/main/java/org/apache/activemq/broker/region/virtual/BaseVirtualDestinationFilter.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/virtual/MappedQueueFilter.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/virtual/SelectorAwareVirtualTopicInterceptor.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/virtual/VirtualTopicInterceptor.java
activemq-unit-tests/src/test/java/org/apache/activemq/broker/virtual/VirtualTopicSelectorWithAnotherInterceptorTest.java

`next` is not guaranteed  to be Topic. If there is plugin that injects another `DestinationInterceptor`, the code will fail with `ClassCastException`.
Added a method to correctly unwrap next.
Ran:
* AMQ4899Test.java
* VirtualTopicSelectorTest.java
* JavaVirtualDestTest.java
* SelectorAwareVTThatDropsMessagesWhenNoConsumer.java
* TwoBrokerVirtualTopicSelectorAwareForwardingTest.java
* VirtualConsumerDemandTest.java
* VirtualTopicSelectorWithAnotherInterceptorTest.java
to make sure there is no regression

[AMQ-9530]Fix SelectorAwareVirtualTopicInterceptor ClassCastException if next is not Topic.

---

activemq-unit-tests/src/test/java/org/apache/activemq/ActiveMQSslConnectionFactoryTest.java

**What problems does this PR solve?**
Add test coverage to ensure socket parameters can be set for tcp and ssl connections. 
**Why is it beneficial to merge into ActiveMQ?**
The tests provide confidence and prevent future issues like [AMQ-9473](https://issues.apache.org/jira/browse/AMQ-9473). 
**How do you make sure this PR is well tested?**
_Test A_
Ran the two new units tests and verified success.
_Test B_
Edited the `IntrospectionSupport` class to comment out the following:
```
//            if (target instanceof SSLServerSocket) {
//                // overcome illegal access issues with internal implementation class
//                clazz = SSLServerSocket.class;
//            } else if (target instanceof javax.net.ssl.SSLSocket) {
//                // overcome illegal access issues …
```

AMQ-9478 Add unit tests for tcp & ssl socket properties

---

pom.xml

[NO-JIRA] Remove no-op 'optimize' flag to maven-compiler-plugin 

---

activemq-broker/src/main/java/org/apache/activemq/broker/region/policy/PolicyEntry.java
activemq-unit-tests/src/test/java/org/apache/activemq/bugs/AMQ3157Test.java
activemq-unit-tests/src/test/java/org/apache/activemq/bugs/AMQ3324Test.java
activemq-unit-tests/src/test/java/org/apache/activemq/usecases/RequestReplyNoAdvisoryNetworkTest.java

``PolicyEntry.setInactiveTimoutBeforeGC(long inactiveTimoutBeforeGC)`` is deprecated, and the deprecation note suggests using ``PolicyEntry.setInactiveTimeoutBeforeGC(long setInactiveTimeoutBeforeGC)``.
The deprecation note has a typo, it says to use the ``getInactiveTimeoutBeforeGC`` for the deprecated ``setInactiveTimoutBeforeGC``, but should be ``setInactiveTimeoutBeforeGC``

[AMQ-9543] Replace use of deprecated setInactiveTimoutBeforeGC in unit tests

---

activemq-unit-tests/src/test/java/org/apache/activemq/bugs/AMQ2512Test.java
activemq-unit-tests/src/test/java/org/apache/activemq/bugs/AMQ2616Test.java
activemq-unit-tests/src/test/java/org/apache/activemq/bugs/VerifySteadyEnqueueRate.java
activemq-unit-tests/src/test/java/org/apache/activemq/perf/KahaDBQueueTest.java
activemq-unit-tests/src/test/java/org/apache/activemq/store/kahadb/KahaDBFastEnqueueTest.java

Cleaning in activemq-unit-tests to minimize deprecated warnings when building.
``MessageDatabase.setEnableJournalDiskSyncs(boolean enableJournalDiskSyncs)`` is deprecated, and the note suggests to use ``MessageDatabase.setJournalDiskSyncStrategy(String journalDiskSyncStrategy)`` instead.

[AMQ-9542] Replace use of deprecated setEnableJournalDiskSyncs

---

activemq-broker/src/main/java/org/apache/activemq/broker/jmx/DestinationView.java
activemq-broker/src/main/java/org/apache/activemq/broker/jmx/DestinationViewMBean.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/BaseDestination.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/Destination.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/DestinationFilter.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/DestinationStatistics.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/DurableTopicSubscription.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/Queue.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/Topic.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/TopicSubscription.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/policy/PolicyEntry.java
activemq-broker/src/main/java/org/apache/activemq/store/MessageStoreSubscriptionStatistics.java
activemq-client/src/main/java/org/apache/activemq/management/JCAConnectionPoolStatsImpl.java
activemq-client/src/main/java/org/apache/activemq/management/JCAConnectionStatsImpl.java
activemq-client/src/main/java/org/apache/activemq/management/JMSEndpointStatsImpl.java
activemq-client/src/main/java/org/apache/activemq/management/JMSSessionStatsImpl.java
activemq-client/src/main/java/org/apache/activemq/management/MessageFlowStats.java
activemq-client/src/main/java/org/apache/activemq/management/MessageFlowStatsImpl.java
activemq-client/src/main/java/org/apache/activemq/management/StatisticImpl.java
activemq-client/src/main/java/org/apache/activemq/management/StatsImpl.java
activemq-client/src/main/java/org/apache/activemq/management/UnsampledStatistic.java
activemq-client/src/main/java/org/apache/activemq/management/UnsampledStatisticImpl.java
activemq-client/src/main/java/org/apache/activemq/management/UnsampledStatsImpl.java
activemq-client/src/test/java/org/apache/activemq/management/UnsampledStatisticsTest.java
activemq-runtime-config/src/test/java/org/apache/activemq/PolicyEntryTest.java
activemq-runtime-config/src/test/resources/org/apache/activemq/policyEntryTest-policy-advancedMessageStatistics-mod.xml
activemq-runtime-config/src/test/resources/org/apache/activemq/policyEntryTest-policy-advancedMessageStatistics.xml
activemq-unit-tests/src/test/java/org/apache/activemq/network/NetworkAdvancedStatisticsTest.java
activemq-unit-tests/src/test/resources/org/apache/activemq/network/localBroker-advancedNetworkStatistics.xml
activemq-unit-tests/src/test/resources/org/apache/activemq/network/remoteBroker-advancedNetworkStatistics.xml

[AMQ-8463] Add advancedMessageStatistics feature

---

activemq-amqp/src/main/java/org/apache/activemq/transport/amqp/AmqpNioTransport.java
activemq-broker/src/main/java/org/apache/activemq/transport/auto/AutoTcpTransportServer.java
activemq-broker/src/main/java/org/apache/activemq/transport/auto/nio/AutoNIOSSLTransportServer.java
activemq-broker/src/main/java/org/apache/activemq/transport/nio/AutoInitNioSSLTransport.java
activemq-client/src/main/java/org/apache/activemq/transport/nio/NIOSSLTransport.java
activemq-client/src/main/java/org/apache/activemq/transport/nio/NIOTransport.java
activemq-client/src/main/java/org/apache/activemq/transport/tcp/TcpTransport.java
activemq-mqtt/src/main/java/org/apache/activemq/transport/mqtt/MQTTNIOSSLTransport.java
activemq-mqtt/src/main/java/org/apache/activemq/transport/mqtt/MQTTNIOTransport.java
activemq-stomp/src/main/java/org/apache/activemq/transport/stomp/StompNIOSSLTransport.java
activemq-stomp/src/main/java/org/apache/activemq/transport/stomp/StompNIOTransport.java

Switch to using an AtomicInteger for tracking bytes received in a TcpTransport. This makes incrementing the counter an atomic operation. Previously a volatile int was used and incrementing volatiles is not atomic because it's a 3 step process of read, update, set.
This also makes a small fix to ensure that the full initialization buffer will always be entirely read and processed when using the auto+nio+ssl transport. Previous the code assumed only the first command was stored in the initialization buffer but technically more bytes could exist for a future command (even if unlikely with the current Java implementation).

AMQ-9658 - Properly increment transport receive counter

---

activemq-broker/src/main/java/org/apache/activemq/store/MessageRecoveryContext.java
activemq-broker/src/main/java/org/apache/activemq/store/MessageStore.java
activemq-broker/src/main/java/org/apache/activemq/store/ProxyMessageStore.java
activemq-broker/src/main/java/org/apache/activemq/store/memory/MemoryMessageStore.java
activemq-broker/src/test/java/org/apache/activemq/store/MessageRecoveryContextTest.java
activemq-console/src/main/java/org/apache/activemq/console/command/store/StoreBackup.java
activemq-jdbc-store/src/main/java/org/apache/activemq/store/jdbc/JDBCMessageStore.java
activemq-kahadb-store/src/main/java/org/apache/activemq/store/kahadb/KahaDBStore.java
activemq-kahadb-store/src/main/java/org/apache/activemq/store/kahadb/TempKahaDBStore.java
activemq-unit-tests/src/test/java/org/apache/activemq/broker/region/cursors/StoreQueueCursorOrderTest.java
activemq-unit-tests/src/test/java/org/apache/activemq/store/kahadb/KahaDBOffsetRecoveryListenerTest.java

Example usage:
```
./bin/activemq backup --filename=backup.tar.gz --indexes=0,1,5,7,1000,1001     
```

[AMQ-9646] Support selecting specific messages for command line backup

---

assembly/src/release/bin/activemq

When ActiveMQ starts up with `./bin/activemq console`, there is double slash (`//`) shows in the output, example:
*  ... Configurations are loaded in the following order: (omit...)/apache-activemq-6.2.0-SNAPSHOT//bin/setenv
*  .... INFO: Creating pidfile  (omit...)/apache-activemq-6.2.0-SNAPSHOT//data/activemq.pid
*  ... -Dactivemq.classpath= (omit...)/apache-activemq-6.2.0-SNAPSHOT//conf
This fix uses  `Parameter Expansion` which is  a POSIX standard feature in shell ( reference [doc](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02)) . The syntax  `"${ACTIVEMQ_BASE%/}/data"` meaning it removes the trailing `/` if  `$ACTIVEMQ_BASE` ends with a `/`, otherwise it does nothing.
* Apply this to both  `$ACTIVEMQ_HOME` and `$ACTIVEMQ_BASE` where they are …

[AMQ-9645] Fix double slash in path

---

activemq-ra/src/main/java/org/apache/activemq/ra/ServerSessionImpl.java
activemq-ra/src/main/java/org/apache/activemq/ra/ServerSessionPoolImpl.java
activemq-ra/src/test/java/org/apache/activemq/ra/ServerSessionImplTest.java
pom.xml

This PR fixes a couple of issues in the RA.
- move the running flag to a non-blocking approach (remove synchronized on a mutex and use AtomicBoolean)
- update the running to false if we can shedule a task in the worker
- move the listener initialization to the #start which is functionally better and avoid stacking messages in the session while it's not started
- avoid pulling a stale (or not running) session from the pool if we can find otherwise

AMQ-9693: avoid synchronized blocks

---

activemq-broker/src/main/java/org/apache/activemq/broker/region/DurableTopicSubscription.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/PrefetchSubscription.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/Topic.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/cursors/AbstractStoreCursor.java
activemq-broker/src/main/java/org/apache/activemq/broker/region/cursors/TopicStorePrefetch.java
activemq-broker/src/main/java/org/apache/activemq/store/MessageStore.java
activemq-broker/src/main/java/org/apache/activemq/store/ProxyMessageStore.java
activemq-broker/src/main/java/org/apache/activemq/store/ProxyTopicMessageStore.java
activemq-broker/src/main/java/org/apache/activemq/store/TopicMessageStore.java
activemq-broker/src/main/java/org/apache/activemq/store/memory/MemoryMessageStore.java
activemq-broker/src/main/java/org/apache/activemq/store/memory/MemoryTopicMessageStore.java
activemq-jdbc-store/src/main/java/org/apache/activemq/store/jdbc/JDBCMessageStore.java
activemq-jdbc-store/src/main/java/org/apache/activemq/store/jdbc/JDBCTopicMessageStore.java
activemq-kahadb-store/src/main/java/org/apache/activemq/store/kahadb/KahaDBStore.java
activemq-kahadb-store/src/main/java/org/apache/activemq/store/kahadb/TempKahaDBStore.java
activemq-unit-tests/src/test/java/org/apache/activemq/JmsSendReceiveWithMessageExpirationTest.java
activemq-unit-tests/src/test/java/org/apache/activemq/broker/MessageExpirationTest.java
activemq-unit-tests/src/test/java/org/apache/activemq/broker/region/cursors/AbstractPendingMessageCursorTest.java
activemq-unit-tests/src/test/java/org/apache/activemq/broker/region/cursors/StoreCursorRemoveFromCacheTest.java
activemq-unit-tests/src/test/java/org/apache/activemq/broker/region/cursors/StoreQueueCursorOrderTest.java
activemq-unit-tests/src/test/java/org/apache/activemq/bugs/MessageExpirationReaperTest.java
activemq-unit-tests/src/test/java/org/apache/activemq/store/kahadb/KahaDBRecoverExpiredTest.java

This commit fixes multiple problems with handling message expiration on durable topic subscriptions.
1) Memory usage tracking is fixed on expiration by correctly decrementing the counter inside AbstractStoreCursor when calling the remove(message) method, which was previously missed. 2) A new refrence type is used to wrap references in TopicStorePrefetch so that if multiple subscriptions share a reference in their cursors each one can expire the message. Previously only one would expire as the message would be marked as expired and skipped.
3) On client expiration, the references are properly decremented so memory tracking is correct.
4) The expiration thread for Topics has been improved to be much more efficient for KahaDB by only scanning for expired messages if there are durables …

AMQ-9698 - Fix message expiration on durable subs

---

assembly/src/release/docs/user-guide.html

This PR addresses a configuration issue that caused the demo to fail during startup due to an XML parsing error in jetty.xml.
Before this change, starting the demo threw the following error:
``` 
ERROR | Failed to load: file [/Users/user/workspace/activemq-brokers/apache-activemq-6.1.6/examples/conf/activemq-demo.xml], reason: IOException parsing XML document from file [/Users/user/workspace/activemq-brokers/apache-activemq-6.1.6/examples/conf/jetty.xml]
```
This was caused by the application not being able to resolve jetty.xml from the filesystem path. ~~By updating the reference to use the classpath and ensuring the correct path is included, this issue is now resolved.~~
Added instructions to copy `jetty.xml` to `example/conf` to access web demos that fixes the issue.

add instructions to copy jetty.xml to example/conf to access web demos

---

assembly/src/release/bin/activemq

lib is useless in the classpath (resolved by ActiveMQ `main`), but keep user custom classpath.

AMQ-7517: Remove lib in the default classpath

---

assembly/src/release/conf/jetty.xml

This change fixes an issue unintentionally introduced by a previous commit where I added the Content-Security-Policy HTTP header to the Web Console application. The "upgrade-insecure-requests" tells the browser to automatically upgrade HTTP requests to HTTPS, which ends up breaking the assets loading in some browsers when running the Web Console with HTTP only.
I tested by browsing all the Web Console tabs in Chrome and Safari.

AMQ-9739: Removed "upgrade-insecure-requests" from the Web Console's Content-Security-Policy header

---

activemq-unit-tests/src/test/java/org/apache/activemq/store/jdbc/JDBCIOExceptionHandlerMockeryTest.java

The original test used JMock and it has issue with newer JDK. Refactored it with Mockito to modernize this test and re-enabled it

[AMQ-9673] refactored JDBCIOExceptionHandlerMockeryTest to use Mockito and re-enabled the test
